apiVersion: v1
kind: PersistentVolume
metadata:
  name: psql-pv
  labels:
    type: local
    app: psql
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/pv/psql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psql-pvc
  labels:
    app: psql
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
